name: Update IPTV Source

on:
  schedule:
    - cron: '0 20 * * *'  # 每天 UTC 22:00 (北京时间 06:00) 运行
  workflow_dispatch:      # 允许手动触发
# --- 新增的部分 START ---
permissions:
  contents: write
# --- 新增的部分 END ---
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run script
      run: python main.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add live.m3u
        # 这里加个防止报错的逻辑：如果没有更新就不提交
        git commit -m "Auto update IPTV sources" || echo "No changes to commit"
        git push


        # ... 上面是你原本生成文件的步骤 ...

    - name: Trigger Gitee Sync
      # 只有上面成功了才执行
      if: success()
      run: |
        curl -X POST --header 'Content-Type: application/json;charset=UTF-8' \
        "https://gitee.com/api/v5/repos/${{ secrets.GITEE_USER }}/${{ github.event.repository.name }}/sync" \
        -d '{"access_token":"${{ secrets.GITEE_TOKEN }}"}'
